name 'build_cookbook'
maintainer 'Obinna Okpokwasili'
maintainer_email 'obicarl@yahoo.com'
license 'all_rights'
version '0.1.0'

# depends 'carlcomsys_build_cookbook'
depends 'delivery-truck'
# depends 'delivery-sugar'
# depends 'delivery-base'
